#!/usr/bin/env bash
# Installs the immuta-access-control.properties file generated by Immuta.
#
# That file contains an Immuta API key. This script never prints its
# contents, and the destination is gitignored.
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

src="${1:-}"
dest="immuta/immuta-access-control.properties"

if [[ -z "$src" ]]; then
  fail "FILE is required."
  info "Usage:"
  info "  make install-immuta-config FILE=~/Downloads/immuta-access-control.properties"
  exit 2
fi

# Expand a leading ~ so FILE=~/... works when passed through make.
src="${src/#\~/$HOME}"
[[ -f "$src" ]] || die "no such file: $src"

if ! grep -q 'access-control.name' "$src"; then
  die "$(basename "$src") does not look like a Trino access control properties file (no access-control.name)."
fi

mkdir -p immuta
cp "$src" "$dest"
chmod 600 "$dest"
ok "installed to $dest (permissions 600)"

# Safety net: the file holds an API key, so make sure git cannot see it.
if git -C . check-ignore -q "$dest" 2>/dev/null; then
  ok "$dest is gitignored"
else
  fail "$dest is NOT gitignored. Fix .gitignore before committing anything."
fi
if git -C . ls-files --error-unmatch "$dest" >/dev/null 2>&1; then
  fail "$dest is TRACKED by git. Run: git rm --cached $dest"
fi

head1 "Next steps"
if compgen -G 'immuta/plugin/*.jar' >/dev/null; then
  ok "Immuta Trino plugin found in ./immuta/plugin"
  info "  Run 'make restart' to enable Immuta access control, then 'make status'."
else
  warn "No plugin jars in ./immuta/plugin yet, so access control stays disabled."
  info "  This step is manual because the plugin requires Immuta credentials:"
  info "    1. Obtain the Immuta Trino plugin for Trino $(grep -E '^TRINO_VERSION=' .env 2>/dev/null | cut -d= -f2) from Immuta"
  info "       (Immuta support or your tenant's download page). The plugin version"
  info "       must match the Trino version pinned in .env."
  info "    2. Unpack the jars directly into ./immuta/plugin/"
  info "    3. Run 'make restart' and then 'make status'"
fi
